runners:
 AWS-runner:
  image: ubuntu-vitis-2020-1

jobs:   
 build-HW-emu:
  runner: AWS-runner
  type:
   build: hw-emulation
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI 
  output:
   artifact:
    - Emulation-HW/build.sh
    - hw_emu.sh
    - Emulation-HW/launch.sh
    - Emulation-HW/launch.expect
    - Emulation-HW/package
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - aarch64-xilinx-linux.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
  steps:
   - run:
      name: Download files
      command: |
       git clone https://github.com/mwijeyasinghebbx/test_images
       mv test_images/* /tools/Xilinx/Vitis/2020.1/platforms/xilinx_zcu104_base_202010_1/sw/xilinx_zcu104_base_202010_1/xrt/image/
      type: miscellaneous  
   - run:
      name: Run Hardware Emulation Build
      command: Emulation-HW/build.sh
      type: hw-emulation  
 test-hw-emulation:
  runner: AWS-runner
  depends:
   - build-HW-emu
  type:
   test: hw-emulation
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI 
  input: 
   artifact: 
    - build-HW-emu
    - xilinx_zcu104_base_202010_1.zip
  steps:
   - run:
      name: Hardware Emulation
      command: ./hw_emu.sh 
workflows:
 complete-build-test:
  jobs:
   - build-HW-emu
   - test-hw-emulation
