runners:
 AWS-runner:
  image: ubuntu-vitis-2020-1

jobs:   
 build-SW-emu:
  runner: AWS-runner
  type:
   build: software
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - aarch64-xilinx-linux.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
  output:
   artifact:
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/Emulation-SW/build.sh
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/sw_emu.sh
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/Emulation-SW/launch.sh
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/Emulation-SW/launch.expect
  steps:
   - run:
      name: Copy project
      command: cp -r ~/ /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI 
   - run:
      name: Download files
      command: |
       git clone https://github.com/mwijeyasinghebbx/test_images
       mv test_images/* /tools/Xilinx/Vitis/2020.1/platforms/xilinx_zcu104_base_202010_1/sw/xilinx_zcu104_base_202010_1/xrt/image/
      type: miscellaneous 
   - run:
      name: Run Software Emulation Build
      command: |
       cd /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI
       Emulation-SW/build.sh
      type: sw-emulation    
 test-sw-emulation:
  runner: AWS-runner
  depends:
   - build-SW-emu
  type:
   test: sw-emulation
  input: 
   artifact: 
    - build-SW-emu
    - xilinx_zcu104_base_202010_1.zip
  steps:
   - run:
      name: Copy project
      command: cp -r ~/ /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI 
   - run:
      name: Run Software Emulation
      command: ./sw_emu.sh 
   - run:
      name: Software Emulation
      command: echo "Running Software Emulation" 
 build-HW-emu:
  runner: AWS-runner
  type:
   build: hw-emulation
  output:
   artifact:
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/Emulation-HW/build.sh
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/hw_emu.sh
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/Emulation-HW/launch.sh
    - /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI/Emulation-HW/launch.expect
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - aarch64-xilinx-linux.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
  steps:
   - run:
      name: Copy project
      command: cp -r ~/ /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI 
   - run:
      name: Download files
      command: |
       git clone https://github.com/mwijeyasinghebbx/test_images
       mv test_images/* /tools/Xilinx/Vitis/2020.1/platforms/xilinx_zcu104_base_202010_1/sw/xilinx_zcu104_base_202010_1/xrt/image/
      type: miscellaneous  
   - run:
      name: Run Hardware Emulation Build
      command: |
       cd /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI
       Emulation-HW/build.sh
      type: hw-emulation  
 test-hw-emulation:
  runner: AWS-runner
  depends:
   - build-HW-emu
  type:
   test: hw-emulation
  input: 
   artifact: 
    - build-HW-emu
    - xilinx_zcu104_base_202010_1.zip
  steps:
   - run:
      name: Copy project
      command: cp -r ~/ /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI 
   - run:
      name: Hardware Emulation
      command: ./hw_emu.sh 
 build-HW:
  runner: AWS-runner
  type:
   build: hardware
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - petalinux-aarch64-xilinx-linux.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
  steps:
   - run:
      name: Copy project
      command: cp -r ~/ /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI 
   - run:
      name: Build HW
      command: |
       cd /tools/Xilinx/Vitis/2020.1/workspace/test_fast_CI
       Hardware/build.sh
      type: Hardware 
workflows:
 complete-build-test:
  jobs:
   - build-SW-emu
   - test-sw-emulation
   - build-HW-emu
   - test-hw-emulation
   - build-HW
